baseURL: "https://rodrigomiguel.eu"
languageCode: "en-us"
title: "Rodrigo Miguel"
theme: hugo-profile

# Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-

# markup:
#  goldmark:
#    renderer:
#      unsafe: true

Menus:
  main:
    - identifier: blog
      blog: blog
      title: Blog posts
      url: /blogs
      weight: 1

    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Rodrigo Miguel"
  description: Starting point to show myself to the world.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/avatar.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Rodrigo."
    subtitle: "I design media for a living"
    content: "Efficiency aficionado, reliable and technologically talented."
    image: "/avatar.png"
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
    socialLinks:
      fontAwesomeIcons:
      - icon: fab fa-github
        url: https://github.com/rikof1
      - icon: fab fa-linkedin
        url: https://linkedin.com/in/rodmiguel
#      customIcons:
#      - icon: /fav.png
#        url: "https://example.com"

  # About
  about:
    enable: true
    title: "About me"
    image: "/profile-b.png"
    content: |- 
      I am a digital media designer/creator currently pursuing a Master's of Science in Financial Technology. Since young I have always enjoyed pursuing technological abiltiies and learning how-to and can-do with computers.

      Currently, I am living in Aberdeen, UK, while I finish my studies. In my free time I have a couple of projects I want to start and continue, mainly, learning Python and French.
    skills:
      enable: true
      title: "Program proficiency I have acquired over the years:"
      items:
        - "Photoshop"
        - "Ilustrator"
        - "Premiere Pro"
        - "Toon Boom Harmony"
        - "Unity"
        - "HTML"
        - "CSS"
        - "Ionic"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Digital Media Content Manager"
        company: "CAEA Importação Lda"
        companyUrl: "https://caea.pt"
        date: "June 2017 - August 2021 (part-time, summer months)"
        featuredLink:
          enable: true
          name: Facebook page
          url: "https://facebook.com/caeaimportacao"
        content: "Creating Media content was not my only job at the company, therefore, many other skills were developed while working there."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    items:
      - title: "Master of Science - Financial Technology"
        school:
          name: "University of Aberdeen"
          url: "https://abdn.ac.uk/"
        date: "Sept 2022 -"
        # GPA: ""
        # content: |-
      - title: "Bachelor of Science (Hons) - Digital Media"
        school:
          name: "Robert Gordon University"
          url: "https://rgu.ac.uk/"
        date: "Sept 2018 - June 2022"
        GPA: "2:1"
        content: |-
          In this course I started by acquiring experience in HTML and CSS, designing logos and later touching into Animation. Game and App development were also main points of the course.
          
          In Honours year, I completed my reseach and thesis on "Different perspectives in Compositing – Creating assets using 2D & 3D software to be used in fixed camera-shots" with the intent to publish on how different design philosophies would impact development of VFX scenes in time and skill.
  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: VR Fashion Experience - Unity
        content: A Virtual Reality experience with the main focus of presenting fashion-styled items. 
        image:  projects/vr-fashion-experience-unity.png
        featured:
          name: Github repo
          link: https://github.com/RikoF1/vr-fashion-experience-unity
        badges:
        - "Unity"
        - "C#"
        - "Android"
        - "Oculus"
        links:
          - icon: fab fa-github
            url: https://github.com/RikoF1/

      - title: 3D Racing Game - Unity
        content: A racing game consisting of two tracks, with collisions and triggers, from loading to spinning elements.
        image:  /projects/3d-racing-game-unity.png
        featured:
          name: Github repo
          link: https://github.com/RikoF1/3d-racing-game-unity
        badges:
        - "Unity"
        - "C#"
        links:
          - icon: fab fa-github
            url: https://github.com/RikoF1/

      - title: GamaCollection
        content: App directed to game collector's to have their collection values and games in one place.
        image:  /projects/gamacollection-final.png
        featured:
          name: Github repo
          link: https://github.com/RikoF1/gamacollection-final
        badges:
        - "HTML"
        - "JavaScript"
        links:
          - icon: fab fa-github
            url: https://github.com/RikoF1/

      - title: 2D Racing Game - Unity
        content: A racing game consisting of two tracks, with collisions and triggers, from loading to spinning elements.
        image:  /projects/2d-racing-game-unity.png
        featured:
          name: Github repo
          link: https://github.com/RikoF1/2d-racing-game-unity
        badges:
        - "Unity"
        - "C#"
        links:
          - icon: fab fa-github
            url: https://github.com/RikoF1/

      - title: My First Website
        content: My first website, which was blog stylised with a CV attached.
        image:  /projects/my-first-portfolio-website.png
        featured:
          name: Github repo
          link: https://github.com/RikoF1/my-first-portfolio-website
        badges:
        - "HTML"
        - "CSS"
        links:
          - icon: fab fa-github
            url: https://github.com/RikoF1/    
      - title: Processing - Introduction
        content: Couple of projects as an introduction to coding, using Processing language.
        image:  /projects/introduction-processing.png
        featured:
          name: Github repo
          link: https://github.com/RikoF1/introduction-processing
        badges:
        - "Processing"
        links:
          - icon: fab fa-github
            url: https://github.com/RikoF1/    
  
  # Contact
  contact:
    enable: true
    #title: "Custom name"
    content: If you have a query or if you think I can be of help on a project, feel free to contact me. I try to reply promply.
    email: rodmiguel_@outlook.com
    btnName: Contact me

  footer:
    # recentPosts: false
    socialNetworks:
      linkedin: https://www.linkedin.com/in/rodmiguel/
      github: https://github.com/RikoF1/